version: '3'
networks:
  net_shopping_island:

services:
  app:
    build:
      context: .docker/app
      dockerfile: Dockerfile
    container_name: shopping_island_app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net_shopping_island

  nginx:
    image: nginx:1.21
    container_name: shopping_island_nginx
    ports:
      - 8012:80
    volumes:
      - ./:/var/www/app/
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    working_dir: /var/www/app
    networks:
      - net_shopping_island

  database:
    image: mysql:8.0
    container_name: shopping_island_database
    ports:
      - 3312:3306
    environment:
      MYSQL_DATABASE: shopping_island_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - net_shopping_island

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: shopping_island_phpmyadmin
    links:
      - database:db
    depends_on:
      - database
    ports:
      - 8092:80
    environment:
      - PMA_HOST:db
      - PMA_PORT:3300
      - PMA_USER:root
      - PMA_PASSWORD:root
      - UPLOAD_LIMIT:12G
      - MAX_EXECUTION_TIME:1200
    networks:
      - net_shopping_island